### ISSUE TITLE
[request] normalization

### ISSUE THREAD

**Issue by omega3** [mnogu/adjust-sound-volume#1]
Would it be possible for you to introduce normalization? I am not sure if this is the right technical term for this. But I want every sound file to be played in Anki with mpv at the same volume level.

I am on Manjaro Linux.

**Comment by mnogu** [comment]
The loudnorm filter may help though this filter isn't available in the mplayer backend.
https://ffmpeg.org/ffmpeg-filters.html#loudnorm

I will try to implement the feature with the filter.

**Comment by omega3** [comment]
According to Anki documentation mpv is a primary player while mplayer is a fallback
https://docs.ankiweb.net/#/media?id=media

> Anki uses a program called mpv (and mplayer as a fallback)

 For mpv I found this comment
https://github.com/mpv-player/mpv/issues/2883#issuecomment-200801164

Would be great if you could make it so that it can work in the situation when on one card there are a number of sound files from different sources with different sound volume levels. That would be huge improvement to Anki.

**Comment by mnogu** [comment]
I upload a new version to AnkiWeb. You can use the new feature by checking "Enable loudness normalization" in the add-on dialog.

**Comment by eyalroz** [comment]
@mnogu : I'm very interested in this feature,, but have never used mpv except through gnome-mpv/celluloid. Would you mind elaborating a bit about how it might be possible to try this? e.g. where one would go to read about using add-ons and "AnkiWeb"?

**Comment by utuhiro78** [comment]
I wrote [mpv-adjustvol](https://github.com/utuhiro78/mpv-adjustvol). It reads the first 60 seconds (default) of movie/music files to detect max volume, then it plays them with adjusted sound volume. It only takes 0.2 seconds to detect max volume, and it doesn't add any changes to original files.

```
sudo pacman -S --needed ruby mpv ffmpeg
mkdir mpv_test
cd mpv_test/
wget https://github.com/utuhiro78/mpv-adjustvol/archive/refs/heads/main.zip
unzip main.zip
mv */mpv-adjustvol .
chmod a+x mpv-adjustvol
./mpv-adjustvol files
```
