### ISSUE TITLE
Add 'dual-mono' option

### ISSUE THREAD

**Issue by archiif** [mnogu/adjust-sound-volume#3]
I have a lot of mono audio files in my collection, which doesn't work well with the default `loudnorm` options (these files usually sound way too quiet with the filter). To deal with mono audio files properly, you need to set the `dual_mono` option in the `loudnorm` filter to `true`.
So it would be nice if this option can be added to the settings menu.

**Comment by mnogu** [comment]
I have uploaded a new version to AnkiWeb. You can use the new feature by checking "Treat mono input as dual-mono" in the add-on dialog.

**Comment by archiif** [comment]
Thanks, it works!
