### ISSUE TITLE
Volume adjustment does not work with audio files with the `.mka` extension 

### ISSUE THREAD

**Issue by archiif** [mnogu/adjust-sound-volume#4]
Audio normalization does not seem to work with audio files with the `opus` codec
I've uploaded a sample file here:
[CpCXzX55bJE_PT00H41M21.230S_PT00H41M42.310S.zip](https://github.com/mnogu/adjust-sound-volume/files/8056617/CpCXzX55bJE_PT00H41M21.230S_PT00H41M42.310S.zip)
Try to tweak the `Integrated loudness` slider and you'll notice that the volume of other audio files will get affected while this particular file does not.
I'm using Anki 2.1.49 (dc80804a)⁩ on Windows 10

**Comment by archiif** [comment]
I've also tried to open the file directly using `mpv --af=loudnorm=I=-21` but it works just fine, so I don't think it's an mpv issue.

**Comment by archiif** [comment]
Actually, I also noticed that the volume control also does not work at all on these `opus` files. Really bizzare.

**Comment by archiif** [comment]
Okay, I've realized it's not the codec that is the problem, it's the file extension. Once I've renamed the extension into `.opus`, for some reason the volume controls now takes affect.
I can rename the thousands of files I have via Python + AnkiConnect, but if this can be fixed via the extension instead I would really appreciate that.

**Comment by mnogu** [comment]
Anki doesn't seem to regard a `.mka` file as an audio file and this issue seems to be a bug (or a specification) of Anki. I don't know there is a way to address this issue in an Anki add-on.

https://github.com/ankitects/anki/blob/5e1432ff6b6f4ed21750a4496f6b1cd422839db0/qt/aqt/sound.py#L84-L94
```python
AUDIO_EXTENSIONS = {
    "3gp",
    "flac",
    "m4a",
    "mp3",
    "oga",
    "ogg",
    "opus",
    "spx",
    "wav",
}
```

https://github.com/ankitects/anki/blob/5e1432ff6b6f4ed21750a4496f6b1cd422839db0/qt/aqt/editor.py#L61-L83
```python
audio = (
    "3gp",
    "aac",
    "avi",
    "flac",
    "flv",
    "m4a",
    "mkv",
    "mov",
    "mp3",
    "mp4",
    "mpeg",
    "mpg",
    "oga",
    "ogg",
    "ogv",
    "ogx",
    "opus",
    "spx",
    "swf",
    "wav",
    "webm",
)
```

**Comment by archiif** [comment]
Oh well, in the end I realized that I can just use `mpv.conf` to add audio normalization or any other customizations that I want.
