### ISSUE TITLE
 Compatibility with the current version of Anki (23.10.1)

### ISSUE THREAD

**Issue by rwmpelstilzchen** [mnogu/adjust-sound-volume#9]
I’ve just updated Anki from 2.1.65 to ⁨23.10.1 (`fac9e0e`)⁩ and now the add-on doesn’t work. The debug info has this error message:

    Anki 23.10.1 (fac9e0e) Python 3.11.6 Qt 6.6.1 PyQt 6.6.1
    Platform: Linux-6.6.7-arch1-1-x86_64-with-glibc2.38
    Flags: frz=False ao=True sv=3
    Add-ons, last update check: 2023-12-14 23:00:56
    
    When loading Adjust Sound Volume:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/aqt/addons.py", line 245, in loadAddons
        __import__(addon.dir_name)
      File "/home/foo/.local/share/Anki2/addons21/2123044452/__init__.py", line 200, in <module>
        action.triggered.connect(VolumeDialog(mw).show)
                                 ^^^^^^^^^^^^^^^^
      File "/home/foo/.local/share/Anki2/addons21/2123044452/__init__.py", line 113, in __init__
        volume_label, self.volume_slider, self.volume_spin_box = _create_config_widgets(
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/foo/.local/share/Anki2/addons21/2123044452/__init__.py", line 85, in _create_config_widgets
        label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
                            ^^^^^^^^^^^^^^^^^^^^^
    AttributeError: type object 'QSizePolicy' has no attribute 'Expanding'

**Comment by rwmpelstilzchen** [comment]
The last commits solve the problem. Based on a superficial test, the add-on seems to work well now. I’d assume the next step is to upload the new version to AnkiWeb (https://ankiweb.net/shared/info/2123044452).

**Comment by mnogu** [comment]
I've uploaded a new version.

**Comment by mnogu** [comment]
I believe v0.0.6 resolved this issue.
https://github.com/mnogu/adjust-sound-volume/releases/tag/v0.0.6
